apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rails-k8s-demo.fullname" . }}-rails
  labels:
    {{- include "rails-k8s-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.rails.replicaCount }}
  selector:
    matchLabels:
      {{- include "rails-k8s-demo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "rails-k8s-demo.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "rails-k8s-demo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          command:
            - rails
          args:
            - "server"
            - "-b"
            - "0.0.0.0"
          # TODO: Figure out how to query the actual pod
          # livenessProbe:
          #   httpGet:
          #     scheme: HTTPS
          #     host: demo.lewagon.co
          #     path: /
          #     port: 443
          #   timeoutSeconds: 5
          #   failureThreshold: 3
          #   periodSeconds: 5
          # readinessProbe:
          #   httpGet:
          #     scheme: HTTPS
          #     host: demo.lewagon.co
          #     path: /
          #     port: 443
          #   timeoutSeconds: 5
          #   failureThreshold: 3
          #   initialDelaySeconds: 30
          envFrom:
          - configMapRef:
              name: common-env
          {{if .Values.dbConnectionString }}
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-connection-string
                key: db_connection_string
          {{ end }}
          {{if .Values.railsMasterKey }}
          env:
          - name: RAILS_MASTER_KEY
            valueFrom:
              secretKeyRef:
                name: rails-master-key
                key: rails_master_key
          {{ end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
