apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rails-k8s-demo.fullname" . }}-sidekiq
  labels:
{{ include "rails-k8s-demo.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.sidekiq.replicaCount }}
  selector:
    matchLabels:
      {{- include "rails-k8s-demo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: background
  template:
    metadata:
      labels:
        {{- include "rails-k8s-demo.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: background
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: sidekiqalive
              containerPort: 7433
          command:
            - bundle
            - exec
            - sidekiq
          args:
            - "-C"
            - "config/sidekiq.yml"
          livenessProbe:
            httpGet:
              path: /
              port: 7433
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 7433
            initialDelaySeconds: 30 # app specific. Time your sidekiq takes to start processing.
          envFrom:
          - configMapRef:
              name: common-env
          {{if .Values.dbConnectionString }}
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-connection-string
                key: db_connection_string
          {{ end }}
          {{if .Values.railsMasterKey }}
          env:
          - name: RAILS_MASTER_KEY
            valueFrom:
              secretKeyRef:
                name: rails-master-key
                key: rails_master_key
          {{ end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      # Dafault helm
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
