version: "3.4"
x-template-app: &template-app
  build:
    context: ".seatrain"
    dockerfile: "Dockerfile.dev"
    args:
      RUBY_VERSION: 2.6.6
      PG_MAJOR: 12
      NODE_MAJOR: 12
      YARN_VERSION: 1.22.5
      BUNDLER_VERSION: 2.1.4
  image: rails-k8s-demo:dev
  tmpfs:
    - "/tmp"
  stdin_open: true
  tty: true
  volumes:
    - ".:/app:cached"
    - rails_cache:/app/tmp/cache
    - bundle:/usr/local/bundle
    - node_modules:/app/node_modules
    - packs:/app/public/packs
    - ".psqlrc:/root/.psqlrc:ro"
    # TODO: Don't leave those values here if not used for first release
    - ~/code/lewagon/seatrain:/root/code/lewagon/seatrain
    - /var/run/docker.sock:/var/run/docker.sock
    - ~/.kube/config:/root/.kube/config
    - ~/.config/doctl/config.yaml:/root/.config/doctl/config.yaml
  environment:
    - NODE_ENV=development
    - RAILS_ENV=${RAILS_ENV:-development}
    - REDIS_URL=redis://redis:6379/
    - DATABASE_URL=postgres://postgres:postgres@postgres:5432
    - BOOTSNAP_CACHE_DIR=/usr/local/bundle/bootsnap
    - WEBPACKER_DEV_SERVER_HOST=webpacker
    - WEB_CONCURRENCY=1
    - HISTFILE=/app/log/.pry_history
    - PSQL_HISTFILE=/app/log/.psql_history
    - EDITOR=vi
services:
  app:
    <<: *template-app
    command: irb
    depends_on:
      - postgres
      - redis
  rails:
    <<: *template-app
    command:
      - bash
      - "-c"
      - rm -f /app/tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0
    ports:
      - 3000:3000
    depends_on:
      - app
  sidekiq:
    <<: *template-app
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - app
  webpacker:
    <<: *template-app
    command: bundle exec webpack-dev-server
    ports:
      - 3035:3035
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - RAILS_ENV=${RAILS_ENV:-development}
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
  postgres:
    image: postgres:11.1
    volumes:
      - ".psqlrc:/root/.psqlrc:ro"
      - postgres:/var/lib/postgresql/data
      - "./log:/root/log:cached"
    environment:
      - PSQL_HISTFILE=/root/log/.psql_history
    ports:
      - 5432
  redis:
    image: redis:4.0.14-alpine
    volumes:
      - redis:/data
    ports:
      - 6379
volumes:
  postgres:
  redis:
  bundle:
  node_modules:
  rails_cache:
  packs:
