apiVersion: v1
kind: ConfigMap
metadata:
  name: common-env
  annotations:
    helm.sh/hook: pre-upgrade, pre-install
    helm.sh/hook-weight: "-1"
data:
  REDIS_URL: redis://{{ .Release.Name }}-redis-master.default.svc.cluster.local
{{- range $key, $value := .Values.commonEnv }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
