# INSIDE CHART

global:
  fullnameOverride: ""

  image:
    repository: ""
    tag: latest
    pullPolicy: Always
    pullSecret: ""

  rails:
    replicaCount: 1
    resources: {}
    livenessProbe: {}
    readinessProbe: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podSecurityContext: {}
    securityContext: {}

  sidekiq:
    replicaCount: 1
    resources: {}
    livenessProbe: {}
    readinessProbe: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podSecurityContext: {}
    securityContext: {}

  # ENV variables declared here will be set for both Rails and Sidekiq pods
  commonEnv: {}

  # TODO: Find better names for config/secret keys
  commonSecrets: {}

  db:
    prepareJob:
      enabled: false

  service:
    type: ClusterIP
    port: 80

  https:
    enabled: false
    certificateEmail: ""

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - host: example.com